### ISSUE TITLE
Create a Readme File and add detailed structure about the project

### ISSUE THREAD

**Issue by kumarshantanu01** [Webwiznitr/Hacktoberfest-Tulip#1]
Here is an example
![image](https://github.com/Webwiznitr/Hacktoberfest-Tulip/assets/76111005/b40e43c1-1c44-4807-8039-b0526d007b83)

**Comment by shivamkasaudhan** [comment]
Hi @kumarshantanu01,
Please assign this issue to me. I'd like to work on it under Hacktoberfest 2023.
Thank you!
