### ISSUE TITLE
Migrate the initiated server from js to ts.

### ISSUE THREAD

**Issue by AmreetKumarkhuntia** [Webwiznitr/Hacktoberfest-Tulip#14]
You can refer here for the migration - 
https://medium.com/@mhuckstepp/step-by-step-guide-to-convert-an-existing-express-node-js-backend-to-typescript-931e435ea95d
https://blog.phillipninan.com/how-to-convert-expressjs-to-typescripthttps://blog.phillipninan.com/how-to-convert-expressjs-to-typescript

**Comment by ad-astra-per-ardua** [comment]
@AmreetKumarkhuntia Hi, can i try this?

**Comment by AmreetKumarkhuntia** [comment]
@d982h8st7 sure

**Comment by AmreetKumarkhuntia** [comment]
This should not take a lot of time try to finish it up fast.

**Comment by ad-astra-per-ardua** [comment]
Sure, working on it right now.
