### ISSUE TITLE
Create a navbar component for Client

### ISSUE THREAD

**Issue by AmreetKumarkhuntia** [Webwiznitr/Hacktoberfest-Tulip#6]
Create a navbar component for the Client. 
Any UI can be referred to for this.

**Comment by jude-san** [comment]
hi @AmreetKumarkhuntia please assign to me.

**Comment by sujithyadav998** [comment]
assign me this

**Comment by AmreetKumarkhuntia** [comment]
@jude-san Since you asked first I have assigned the task to you.

**Comment by jude-san** [comment]
> @jude-san Since you asked first I have assigned the task to you.

thanks

**Comment by Teja-11** [comment]
Can I work on this or is it resolved?

**Comment by AmreetKumarkhuntia** [comment]
@Teja-11 go on u can work on this I am reassigning this to u
