### ISSUE TITLE
React Router setup

### ISSUE THREAD

**Issue by AmreetKumarkhuntia** [Webwiznitr/Hacktoberfest-Tulip#8]
This is a good issue if you want to learn about react router.

Refer about routing and react router here - https://reactrouter.com/en/main

**Comment by saakshi002** [comment]
Hi, @AmreetKumarkhuntia can you assign me this task?

**Comment by AmreetKumarkhuntia** [comment]
@saakshi002 ya you can take up this issue.

**Comment by AmreetKumarkhuntia** [comment]
If you any issue with the task you can ask up here.

**Comment by ad-astra-per-ardua** [comment]
@AmreetKumarkhuntia Hi, can i join this?

**Comment by AmreetKumarkhuntia** [comment]
@d982h8st7 you can ask @saakshi002 fot this. If you want you can team up for this.

**Comment by ad-astra-per-ardua** [comment]
@saakshi002  I've already done this. If you need any help, feel free to ask me. :>

**Comment by AmreetKumarkhuntia** [comment]
@saakshi002 please reply asap if you are still working otherwise I will reassign this issue.

**Comment by AmreetKumarkhuntia** [comment]
@d982h8st7 do let me know if u have a pull request ready.

**Comment by AmreetKumarkhuntia** [comment]
Will check it out
