### ISSUE TITLE
Add Contribution rules and guidelines.

### ISSUE THREAD

**Issue by AmreetKumarkhuntia** [Webwiznitr/Hacktoberfest-Tulip#9]
Refer to any other open source project and add the documentation into a contribution folder as a readme file.

**Comment by AmreetKumarkhuntia** [comment]
More can be referred on the main readme file on this repo

**Comment by Amir-Helali** [comment]
@AmreetKumarkhuntia I can tackle this issue if that is okay with you.

**Comment by AmreetKumarkhuntia** [comment]
@Amir-Helali I'm closing that issue please create a separate branch in your repo and send the pull request with proper syntax. Thank you !!!

**Comment by AmreetKumarkhuntia** [comment]
Rename the pull request to Added contributions and in the description you can keep added code_of_conduct and contribution. md .

**Comment by Amir-Helali** [comment]
Ok will do.
